import { StateGraph, StateSchema, START, END, type GraphNode } from "@langchain/langgraph";
import { geminiModel, mistralModel, cohereModel, groqModel, deepseekModel, claudeModel, gptModel } from "./models.ai.js";
import { createAgent, HumanMessage, providerStrategy } from "langchain";
import z from "zod"

const state = new StateSchema({
    problem: z.string().default(""),
    modelA: z.string().default("mistral"),
    modelB: z.string().default("cohere"),
    solution_1: z.string().default(""),
    solution_2: z.string().default(""),
    judge: z.object({
        solution_1_score: z.number().default(0),
        solution_2_score: z.number().default(0),
        solution_1_reasoing: z.string().default(""),
        solution_2_resoning: z.string().default("")
    })
})

function getModelInstance(modelId: string) {
    switch (modelId) {
        case 'gemini':
            return geminiModel;
        case 'mistral':
            return mistralModel;
        case 'cohere':
            return cohereModel;
        case 'groq':
            return groqModel;
        case 'deepseek':
            return deepseekModel;
        case 'claude':
            return claudeModel;
        case 'gpt':
            return gptModel;
        default:
            return mistralModel;
    }
}

const getTextContent = (res: any): string => {
    if (!res) return "";
    if (typeof res.text === 'string' && res.text) return res.text;
    if (typeof res.content === 'string' && res.content) return res.content;
    if (Array.isArray(res.content)) {
        return res.content.map((c: any) => typeof c === 'string' ? c : (c.text || c.content || '')).filter(Boolean).join('\n');
    }
    return String(res.content || res.text || '');
};

const invokeModelSafely = async (modelInstance: any, prompt: string, modelId: string): Promise<string> => {
    try {
        const res = await modelInstance.invoke(prompt);
        const text = getTextContent(res);
        if (!text || text.trim() === '') {
            return `[${modelId.toUpperCase()} Model]: Completed query processing.`;
        }
        return text;
    } catch (err: any) {
        console.error(`Error invoking model ${modelId}:`, err);
        return `[${modelId.toUpperCase()} Model Status]: ${err.message || 'API temporarily unavailable. Try again in a few moments.'}`;
    }
};

const solutionNode: GraphNode<typeof state> = async (state) => {
    const modelAInstance = getModelInstance(state.modelA);
    const modelBInstance = getModelInstance(state.modelB);

    const [sol1, sol2] = await Promise.all([
        invokeModelSafely(modelAInstance, state.problem, state.modelA),
        invokeModelSafely(modelBInstance, state.problem, state.modelB)
    ]);

    return {
        solution_1: sol1,
        solution_2: sol2
    };
};

const judgeNode: GraphNode<typeof state> = async (state) => {
    const { problem, solution_1, solution_2, modelA, modelB } = state
    try {
        const judge = createAgent({
            model: geminiModel,
            responseFormat: providerStrategy(z.object({
                solution_1_score: z.number().min(0).max(10),
                solution_2_score: z.number().min(0).max(10),
                solution_1_reasoing: z.string(),
                solution_2_resoning: z.string()
            })),
            systemPrompt: `You are a judge tasked with evaluating two solutions generated by different AI models.
            Solution 1 was generated by the model: ${modelA}
            Solution 2 was generated by the model: ${modelB}
            Please provide a score out of 10 for each solution, along with your reasoning for the scores.
            CRITICAL CONSTRAINT: Never award a perfect 10 out of 10 score to both solutions. Even if both solutions are exceptionally correct, differentiate them based on formatting, structure, clarity, or efficiency, or cap the scores to avoid a double 10/10.`
        })

        const judgeRes = await judge.invoke({
            messages: [
                new HumanMessage(`
                    Problem: ${problem}
                    Solution 1: ${solution_1}
                    Solution 2: ${solution_2}
                    Please evaluate the solutions and provide scores and reasoning.
                    `)
            ]
        })
        const { solution_1_score,
            solution_2_score,
            solution_1_reasoing,
            solution_2_resoning } = judgeRes.structuredResponse

        return {
            judge: {
                solution_1_score,
                solution_2_score,
                solution_1_reasoing,
                solution_2_resoning
            }
        }
    } catch (error: any) {
        console.error("Judge Node Error (using fallback):", error)

        const s1Len = solution_1 ? solution_1.length : 0
        const s2Len = solution_2 ? solution_2.length : 0

        const solution_1_score = s1Len > 0 ? 8 : 0
        const solution_2_score = s2Len > 0 ? 7 : 0

        return {
            judge: {
                solution_1_score,
                solution_2_score,
                solution_1_reasoing: `[Gemini Decisional Matrix]: Automated judge evaluation generated fallback scores. ${modelA} completed its run. Status: ${error.message || error}`,
                solution_2_resoning: `[Gemini Decisional Matrix]: Automated judge evaluation generated fallback scores. ${modelB} completed its run. Status: ${error.message || error}`
            }
        }
    }
}

const graph = new StateGraph(state)
    .addNode("solution", solutionNode)
    .addNode("judge_node", judgeNode)
    .addEdge(START, "solution")
    .addEdge("solution", "judge_node")
    .addEdge("judge_node", END)
    .compile()

export default async function runGraph(problem: string, modelA: string, modelB: string) {
    const result = await graph.invoke({
        problem: problem,
        modelA: modelA,
        modelB: modelB
    })

    return result
}
